# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the build image to "latest" to use the latest stable build image
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Define the documentation type as "mkdocs"
mkdocs:
  configuration: mkdocs.yml

# Define the Python dependencies required to build your documentation
python:
  install:
    - requirements: requirements.txt
